# Generated by Django 2.0.7 on 2018-08-02 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=64)),
                ('Items', models.TextField()),
                ('Status', models.TextField(default='In Cart')),
                ('Price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinner', models.CharField(max_length=64)),
                ('Size', models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], max_length=64)),
                ('Price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=64)),
                ('Items', models.TextField()),
                ('Status', models.TextField(default='Ordered')),
                ('Date', models.DateField(verbose_name=datetime.datetime(2018, 8, 2, 8, 22, 7, 958948))),
                ('Price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PastaDish', models.CharField(max_length=64)),
                ('Price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PizzaDish', models.CharField(choices=[('RG', 'Regular'), ('SC', 'Sicilian')], default='RG', max_length=64)),
                ('Size', models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], default='SM', max_length=64)),
                ('Price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('Num_Toppings', models.CharField(choices=[('Cheese', 'Cheese'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('SPECIAL', 'SPECIAL')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PizzaDish', models.CharField(choices=[('RG', 'Regular'), ('SC', 'Sicilian')], default='RG', max_length=64)),
                ('Size', models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], default='SM', max_length=64)),
                ('Price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('Num_Toppings', models.CharField(choices=[('Cheese', 'Cheese'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('SPECIAL', 'SPECIAL')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salad', models.CharField(max_length=64)),
                ('Price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub', models.CharField(max_length=64)),
                ('Size', models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], max_length=64)),
                ('Price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topps', models.CharField(choices=[('Pepporoni', 'Pepperoni'), ('Sausage', 'Sausage')], max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='Toppings',
            field=models.ManyToManyField(blank=True, to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Toppings',
            field=models.ManyToManyField(null=True, to='orders.Toppings'),
        ),
    ]
