# Generated by Django 2.0.7 on 2018-07-29 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 7, 29, 21, 52, 39, 902770)),
        ),
    ]
