# Generated by Django 2.0.7 on 2018-07-29 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180729_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 7, 29, 21, 53, 45, 561108)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Toppings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Toppings'),
        ),
    ]
