# Generated by Django 2.0.7 on 2018-07-29 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180729_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Toppings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 7, 29, 22, 43, 30, 557192)),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Toppings',
        ),
        migrations.AddField(
            model_name='orders',
            name='Toppings',
            field=models.ManyToManyField(to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='Topps',
            field=models.CharField(choices=[('Pepporoni', 'Pepperoni'), ('Sausage', 'Sausage')], max_length=64),
        ),
    ]
