# Generated by Django 2.0.7 on 2018-07-29 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180729_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 7, 29, 23, 0, 40, 902994)),
        ),
    ]
