# Generated by Django 2.0.7 on 2018-07-31 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180729_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Toppings',
        ),
        migrations.AddField(
            model_name='cart',
            name='Toppings',
            field=models.ManyToManyField(null=True, to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 7, 31, 1, 16, 15, 252579)),
        ),
    ]
